# Generated by Django 4.0.3 on 2022-04-21 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_posttype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='recipe.posttype'),
        ),
    ]
